before_install:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod u+x ./rebar3
language: erlang
otp_release:
    - 19.3.6
    - 20.3.8
    - 21.0.4
install: "true"
script:
    - ./rebar3 do compile && ./rebar3 do ct && ./rebar3  coveralls send
